Siscot-Back/SiscotBackend/config/routes.rb
Rails.application.routes.draw do
  resources :driverroutes
  resources :usrfavs
  resources :ratings
  resources :routes
  resources :drivers
  resources :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

Siscot-Back/SiscotBackend/app/models/driver.rb
class Driver < ApplicationRecord
end

Siscot-Back/SiscotBackend/app/controllers/drivers_controller.rb
class DriversController < ApplicationController
  before_action :set_driver, only: [:show, :edit, :update, :destroy]

  # GET /drivers
  # GET /drivers.json
  def index
    @drivers = Driver.all
  end

  # GET /drivers/1
  # GET /drivers/1.json
  def show
  end

  # GET /drivers/new
  def new
    @driver = Driver.new
  end

  # GET /drivers/1/edit
  def edit
  end

  # POST /drivers
  # POST /drivers.json
  def create
    @driver = Driver.new(driver_params)

    respond_to do |format|
      if @driver.save
        format.html { redirect_to @driver, notice: 'Driver was successfully created.' }
        format.json { render :show, status: :created, location: @driver }
      else
        format.html { render :new }
        format.json { render json: @driver.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /drivers/1
  # PATCH/PUT /drivers/1.json
  def update
    respond_to do |format|
      if @driver.update(driver_params)
        format.html { redirect_to @driver, notice: 'Driver was successfully updated.' }
        format.json { render :show, status: :ok, location: @driver }
      else
        format.html { render :edit }
        format.json { render json: @driver.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /drivers/1
  # DELETE /drivers/1.json
  def destroy
    @driver.destroy
    respond_to do |format|
      format.html { redirect_to drivers_url, notice: 'Driver was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_driver
      @driver = Driver.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def driver_params
      params.require(:driver).permit(:name, :email, :password, :idcard)
    end
end

Siscot-Back/SiscotBackend/app/helpers/drivers_helper.rb
module DriversHelper
end

Siscot-Back/SiscotBackend/app/views/drivers/_form.html.erb
<%= form_with(model: driver, local: true) do |form| %>
  <% if driver.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(driver.errors.count, "error") %> prohibited this driver from being saved:</h2>

      <ul>
      <% driver.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :email %>
    <%= form.text_field :email %>
  </div>

  <div class="field">
    <%= form.label :password %>
    <%= form.text_field :password %>
  </div>

  <div class="field">
    <%= form.label :idcard %>
    <%= form.text_field :idcard %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

Siscot-Back/SiscotBackend/app/views/drivers/edit.html.erb
<h1>Editing Driver</h1>

<%= render 'form', driver: @driver %>

<%= link_to 'Show', @driver %> |
<%= link_to 'Back', drivers_path %>

Siscot-Back/SiscotBackend/app/views/drivers/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Drivers</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Email</th>
      <th>Password</th>
      <th>Idcard</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @drivers.each do |driver| %>
      <tr>
        <td><%= driver.name %></td>
        <td><%= driver.email %></td>
        <td><%= driver.password %></td>
        <td><%= driver.idcard %></td>
        <td><%= link_to 'Show', driver %></td>
        <td><%= link_to 'Edit', edit_driver_path(driver) %></td>
        <td><%= link_to 'Destroy', driver, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Driver', new_driver_path %>

Siscot-Back/SiscotBackend/app/views/drivers/new.html.erb
<h1>New Driver</h1>

<%= render 'form', driver: @driver %>

<%= link_to 'Back', drivers_path %>

Siscot-Back/SiscotBackend/app/views/drivers/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @driver.name %>
</p>

<p>
  <strong>Email:</strong>
  <%= @driver.email %>
</p>

<p>
  <strong>Password:</strong>
  <%= @driver.password %>
</p>

<p>
  <strong>Idcard:</strong>
  <%= @driver.idcard %>
</p>

<%= link_to 'Edit', edit_driver_path(@driver) %> |
<%= link_to 'Back', drivers_path %>