Siscot-Back/SiscotBackend/config/routes.rb
Rails.application.routes.draw do
  resources :driverroutes
  resources :usrfavs
  resources :ratings
  resources :routes
  resources :drivers
  resources :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

Siscot-Back/SiscotBackend/app/models/usrfav.rb
class Usrfav < ApplicationRecord
  belongs_to :user
  belongs_to :route
end

Siscot-Back/SiscotBackend/app/controllers/usrfavs_controller.rb
class UsrfavsController < ApplicationController
  before_action :set_usrfav, only: [:show, :edit, :update, :destroy]

  # GET /usrfavs
  # GET /usrfavs.json
  def index
    @usrfavs = Usrfav.all
  end

  # GET /usrfavs/1
  # GET /usrfavs/1.json
  def show
  end

  # GET /usrfavs/new
  def new
    @usrfav = Usrfav.new
  end

  # GET /usrfavs/1/edit
  def edit
  end

  # POST /usrfavs
  # POST /usrfavs.json
  def create
    @usrfav = Usrfav.new(usrfav_params)

    respond_to do |format|
      if @usrfav.save
        format.html { redirect_to @usrfav, notice: 'Usrfav was successfully created.' }
        format.json { render :show, status: :created, location: @usrfav }
      else
        format.html { render :new }
        format.json { render json: @usrfav.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /usrfavs/1
  # PATCH/PUT /usrfavs/1.json
  def update
    respond_to do |format|
      if @usrfav.update(usrfav_params)
        format.html { redirect_to @usrfav, notice: 'Usrfav was successfully updated.' }
        format.json { render :show, status: :ok, location: @usrfav }
      else
        format.html { render :edit }
        format.json { render json: @usrfav.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /usrfavs/1
  # DELETE /usrfavs/1.json
  def destroy
    @usrfav.destroy
    respond_to do |format|
      format.html { redirect_to usrfavs_url, notice: 'Usrfav was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_usrfav
      @usrfav = Usrfav.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def usrfav_params
      params.require(:usrfav).permit(:user_id, :route_id)
    end
end

Siscot-Back/SiscotBackend/app/helpers/usrfavs_helper.rb
module UsrfavsHelper
end

Siscot-Back/SiscotBackend/app/views/usrfavs/_form.html.erb
<%= form_with(model: usrfav, local: true) do |form| %>
  <% if usrfav.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(usrfav.errors.count, "error") %> prohibited this usrfav from being saved:</h2>

      <ul>
      <% usrfav.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :user_id %>
    <%= form.text_field :user_id %>
  </div>

  <div class="field">
    <%= form.label :route_id %>
    <%= form.text_field :route_id %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

Siscot-Back/SiscotBackend/app/views/usrfavs/edit.html.erb
<h1>Editing Usrfav</h1>

<%= render 'form', usrfav: @usrfav %>

<%= link_to 'Show', @usrfav %> |
<%= link_to 'Back', usrfavs_path %>

Siscot-Back/SiscotBackend/app/views/usrfavs/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Usrfavs</h1>

<table>
  <thead>
    <tr>
      <th>User</th>
      <th>Route</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @usrfavs.each do |usrfav| %>
      <tr>
        <td><%= usrfav.user %></td>
        <td><%= usrfav.route %></td>
        <td><%= link_to 'Show', usrfav %></td>
        <td><%= link_to 'Edit', edit_usrfav_path(usrfav) %></td>
        <td><%= link_to 'Destroy', usrfav, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Usrfav', new_usrfav_path %>

Siscot-Back/SiscotBackend/app/views/usrfavs/new.html.erb
<h1>New Usrfav</h1>

<%= render 'form', usrfav: @usrfav %>

<%= link_to 'Back', usrfavs_path %>

Siscot-Back/SiscotBackend/app/views/usrfavs/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>User:</strong>
  <%= @usrfav.user %>
</p>

<p>
  <strong>Route:</strong>
  <%= @usrfav.route %>
</p>

<%= link_to 'Edit', edit_usrfav_path(@usrfav) %> |
<%= link_to 'Back', usrfavs_path %>